name: Build & Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy nodejs app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          command_timeout: "60m"
          
          script: |
            rm -r padlomoon.com
            git clone git@github.com:PadloMoon/website.git padlomoon.com
            cp secrets/padlo/.env padlomoon.com/.env
            cd padlomoon.com
            docker-compose build
            docker-compose down && docker-compose up -d
            echo "Deployment success"
