name: Build & Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy nodejs app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            rm -r website
            git clone git@github.com:PadloMoon/website.git
            cp secrets/padlo/.mainenv website/.env
            cp secrets/padlo/.frontendenv website/frontend/.env
            cp secrets/padlo/.backendenv website/backend/.env
            cd website
            docker-compose build
            docker-compose down && docker-compose up -d
            echo "Deployment success"
